apiVersion: apps/v1
kind: Deployment
metadata:
  name: velora-mongo
  labels:
    app: velora-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velora-mongo
  template:
    metadata:
      labels:
        app: velora-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-configuration
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-configuration
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-configuration
                  key: MONGO_DATABASE
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-initialisation
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: velora-mongo-pvc
        - name: mongo-initialisation
          configMap:
            name: mongo-initialisation
