apiVersion: apps/v1
kind: Deployment
metadata:
  name: velora-server
  labels:
    app: velora-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velora-server
  template:
    metadata:
      labels:
        app: velora-server
    spec:
      containers:
        - name: server
          image: m11615/velora-server:latest
          ports:
            - containerPort: 3000
