apiVersion: apps/v1
kind: Deployment
metadata:
  name: velora-client
  labels:
    app: velora-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velora-client
  template:
    metadata:
      labels:
        app: velora-client
    spec:
      containers:
        - name: client
          image: m11615/velora-client:latest
          ports:
            - containerPort: 3001
